ErrorBoundaryの導入
TechUni2020/member-site pull request #171
Opened 2022-09-23 03:21 UTC by GitHayato

## ✨ 実装した issue

closed 

## ⛏ 変更内容 / Details of Changes

- 各pageコンポーネント内でTanstack QueryのisErrorを使ってエラーハンドリングしていた箇所を削除し、ErrorBoundaryにキャッチさせるようにした
- Tanstack Query以外のエラーもキャッチさせるようにした

## 💩 やっていないこと
-

## 📸 参考

## ✅ テスト項目
- admin, app全てのページが正しく表示される
- throw new Error()を返すとAppErrorが表示される

2022-09-23 14:58 UTC, shinyamamoto0422 commented on src/components/ui-libraries/AppError.tsx
> +      <AppButton color="blue" radius="md" size="md" onClick={resetErrorBoundary} className="m-2">リトライする</AppButton>
これはtype="button"いらないんですか

2022-09-23 14:58 UTC, shinyamamoto0422 commented on src/components/ui-libraries/AppError.tsx
> +  console.error(error)
これって必要なんですか？

2022-09-23 15:17 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +              )}
これなんですが、なんでFallbackComponentじゃなくてfallbackRenderを選んだんですか？

```
            FallbackComponent={(props) =>
              isAdmin ? (
                <AdminLayout>
                  <AppError {...props} />
                </AdminLayout>
              ) : (
                <AppLayout>
                  <AppError {...props} />
                </AppLayout>
              )
            }
```
これでも正常に動きます（ローカルで試した）

2022-09-23 15:22 UTC, shinyamamoto0422 requested changes

2022-09-23 15:22 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +              )}
動作確認で試した部分なんですが、
例えば

study-meeting.tsxのuseGetAllStudyMeetingでthrow errorした時に
- /study-meetingに行くまでは正常に表示される
- /study-meetingに行くと当然エラーになる
- その後他のページに行くと先までは表示されてたのに、AppErrorが表示される
という動作になるんですが、それはユーザー体験的に大丈夫ですかね。。


https://user-images.githubusercontent.com/83487508/191995958-5b2b2596-4ee6-4d3d-8e90-a39f561a1995.mov

2022-09-23 17:04 UTC, shinyamamoto0422 commented
ただ、普通にめっちゃ便利ですね
ErrorBoundary

2022-09-24 02:29 UTC, GitHayato commented on src/components/ui-libraries/AppError.tsx
> +  console.error(error)
@shinyamamoto0422 
必要ないけど、エラーの内容をどこにも表示させてないから、エラーになって報告受けた時、コンソール見てって言えば解決まで早いかなってw
消したほうがいいなら消す！

2022-09-24 03:21 UTC, GitHayato commented on src/pages/_app.tsx
> +              )}
@shinyamamoto0422 
修正しました 🙇

2022-09-24 03:35 UTC, shinyamamoto0422 commented on src/components/ui-libraries/AppError.tsx
> +  console.error(error)
あー、確かに！それはそうですね！
残しときましょう！

2022-09-26 00:17 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +
返事遅れてすいません！

これって現状としては、エラー出た時にはホームボタンを押したら、リロードされてメンバーページ以外は正常に見れる状態になってますよね。

これって、本元の解決にはなってない気がするんですよね。。。

2022-09-26 00:29 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +
僕が試したので言うと、
- userRepositoryの中にthrow new Error("Not implemented") を書く
- src/pages/member/index.tsx MemberPageの中に、

```
      <QueryErrorResetBoundary>
        {({ reset }) => (
          <ErrorBoundary
            onReset={reset}
            FallbackComponent={(props) => <AppError handleClickBackToHome={handleClickBackToHome} {...props} 
       />}
          >
            <Member />
          </ErrorBoundary>
        )}
      </QueryErrorResetBoundary>
```
を入れる

というのを試したら、いけるんじゃないかと思ったんですが、ダメでしたね、、

2022-09-26 00:37 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +
一旦、 @GitHayato さんの方で試行錯誤してもらって無理そうなら、全然この状態でもいいので、それでマージしちゃいましょう！！

2022-09-26 01:58 UTC, GitHayato commented on src/pages/_app.tsx
> +
@shinyamamoto0422 
おっと、本来の解決とはなんだっけ？

2022-09-26 16:34 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +
すいません、言葉足らずでした。

僕が言ってた本来の解決は
「このPRの前の挙動をErrorBoundaryで実現する」という意味です。

その挙動は
- もし/memberでエラーが出たらエラーコンポーネントが表示される
- ただ、他のページに行っても、正常に表示される
というものです。

ただ、現状の挙動としては
他のページに行ったら正常に表示されずAppErrorが表示される

状態になってます！

という意味でした🙏

2022-09-27 01:54 UTC, shinyamamoto0422 commented on src/pages/_app.tsx
> +
@GitHayato 一応

2022-09-27 01:59 UTC, GitHayato commented on src/pages/_app.tsx
> +
理解した、少し調べる

2022-09-27 14:59 UTC, GitHayato commented
@shinyamamoto0422 
https://github.com/alan2207/bulletproof-react/blob/master/src/providers/app.tsx
Reactのめちゃくちゃ参考になるリポジトリを参考に修正してみた。
具体的には
- そもそもサイドバーを含めたレイアウトを表示せず、Errorコンポーネントのみを表示させる。
- 必ずトップページに遷移させるようにボタンのonClick eventを修正

https://user-images.githubusercontent.com/74091672/192561628-d7f58299-1399-44cb-b883-e86f6c255041.mov

2022-09-29 16:06 UTC, shinyamamoto0422 approved these changes
LGTM

2022-09-29 16:06 UTC, merged